site_name: AppSecTA_Toolchain Map
site_url: "https://geminishkv.github.io/oss_toolchainmap/"

theme:
  name: material

extra_css:
  - stylesheets/custom_table.css

extra_javascript:
  - javascripts/tools-overlay.js
  - javascripts/tools-search.js

nav:
  - "FinDevSecOps Community": index.mdd
  - "Карта инструментов":
      - "Tolchain": research-notes.m
      - "Православные вендора": vendor_rf.md
      - "Зарубежные вендора": external.md
      - "OSS": OSS.md
  - "Заметки": notes.md
  - "About": about.md

plugins:
  - search
  - macros

markdown_extensions:
  - def_list
  - md_in_html
  - attr_list

extra:
  table:
    - division: AppSec
      type:
        - name: SAST
          class:
            - name: "Статический анализатор"
              OSS_tools: docs/tools/AppSec/SAST/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/SAST/PS_tools.yaml

        - name: Attack Surface Analysis
          class:
            - name: "Анализ поверхности атаки"
              OSS_tools: docs/tools/AppSec/Attack_Surface_Analysis/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/Attack_Surface_Analysis/PS_tools.yaml

        - name: IAST
          class:
            - name: "Интерактивный анализатор"
              OSS_tools: docs/tools/AppSec/IAST/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/IAST/PS_tools.yaml

        - name: SCA/OSA
          class:
            - name: "Анализатор"
              OSS_tools: docs/tools/AppSec/SCA_OSA/Analizator/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/SCA_OSA/Analizator/PS_tools.yaml
            - name: "SBOM"
              OSS_tools: docs/tools/AppSec/SCA_OSA/SBOM/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/SCA_OSA/SBOM/PS_tools.yaml

        - name: BCA
          class:
            - name: "Бинарный анализатор"
              OSS_tools: docs/tools/AppSec/BCA/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/BCA/PS_tools.yaml

        - name: DAST
          class:
            - name: "Whitebox Fuzzing"
              OSS_tools: docs/tools/AppSec/DAST/Whitbox_fuzzing/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/DAST/Whitbox_fuzzing/PS_tools.yaml
            - name: "DAST"
              OSS_tools: docs/tools/AppSec/DAST/DAST/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/DAST/DAST/PS_tools.yaml

        - name: MAST
          class:
            - name: "Анализатор MobApp"
              OSS_tools: docs/tools/AppSec/MAST/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/MAST/PS_tools.yaml

        - name: RASP
          class:
            - name: "Анализатор при Runtime"
              OSS_tools: docs/tools/AppSec/RASP/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/RASP/PS_tools.yaml

        - name: API
          class:
            - name: "ApiSec_WAF"
              OSS_tools: docs/tools/AppSec/API/OSS_tools.yaml
              PS_tools: docs/tools/AppSec/API/PS_tools.yaml

    - division: codecoverage
      OSS_tools: docs/tools/codecoverage/OSS_tools.yaml
      PS_tools: docs/tools/codecoverage/PS_tools.yaml

    - division: Application Security Posture Management
      OSS_tools: docs/tools/ASPM/OSS_tools.yaml
      PS_tools: docs/tools/ASPM/PS_tools.yaml

    - division: Container Security
      OSS_tools: docs/tools/Container_Security/OSS_tools.yaml
      PS_tools: docs/tools/Container_Security/PS_tools.yaml

    - division: Secrets Management
      OSS_tools: docs/tools/Secrets_Management/OSS_tools.yaml
      PS_tools: docs/tools/Secrets_Management/PS_tools.yaml

    - division: MLSecOps
      OSS_tools: docs/tools/MLSecOps/OSS_tools.yaml
      PS_tools: docs/tools/MLSecOps/PS_tools.yaml
